# extends:
#   - '@commitlint/config-conventional'

rules:
  # Enforce conventional commits
  type-enum:
    - 2
    - always
    - - feat     # New feature
      - fix      # Bug fixes
      - docs     # Documentation only
      - style    # Formatting, missing semi colons, etc
      - refactor # Code change that neither fixes a bug nor adds a feature
      - perf     # Code change that improves performance
      - test     # Adding missing tests
      - build    # Changes that affect the build system
      - ci       # Changes to CI configuration files and scripts
      - chore    # Other changes that don't modify src or test files
      - revert   # Reverts a previous commit

  # Scope naming convention
  scope-enum:
    - 2
    - always
    - # System-level scopes
      - system
      - boot
      - hardware
      - network
      - security
      # NixOS-specific
      - nixos
      - flake
      - pkgs
      - module
      # Constellation names
      - cassiopeia
      - aquarius
      - ursamajor
      # Core components
      - sops
      - stars
      - rockets
      - asterisms
      # Desktop environments & WMs
      - gnome
      - hyprland
      # Applications
      - nvim
      - firefox
      - kitty
      - zsh
      - btop
      # Subsystems
      - audio
      - video
      - nvidia
      # Development
      - dev
      - python
      - rust
      - nix
      # Documentation
      - readme
      - changelog
      - docs

  # Other rules
  scope-case:
    - 2
    - always
    - - lower-case    # scope must be lower-case
      - kebab-case    # allow kebab-case

  subject-case:
    - 2
    - always
    - - lower-case    # subject must start with lower case

  subject-empty:
    - 2
    - never          # subject cannot be empty

  subject-full-stop:
    - 2
    - never          # subject cannot end with dot

  header-max-length:
    - 2
    - always
    - 72             # keep header (first line) concise

  body-leading-blank:
    - 2
    - always        # body must start with blank line

  footer-leading-blank:
    - 2
    - always        # footer must start with blank line

help: |
  Your commit message should follow this format:
  <type>(<scope>): <subject>
  <BLANK LINE>
  <body>
  <BLANK LINE>
  <footer>

  Examples:
  feat(nvim): add telescope plugin
  fix(audio): correct pipewire configuration
  docs(readme): update installation instructions

  Available types:
  - feat:     New feature
  - fix:      Bug fix
  - docs:     Documentation changes
  - style:    Code style/formatting
  - refactor: Code restructuring
  - perf:     Performance improvements
  - test:     Adding/updating tests
  - build:    Build system changes
  - ci:       CI configuration changes
  - chore:    Maintenance tasks
  - revert:   Revert previous changes
