keys:
  - &primary age15ptmy54dcgrz7aa5k6jjutgrkj9x8cfcecnmy6uqkp2l7m5muvzskdtsnf
  - &c_hercules age1gawacww0wxtfxuaajx0lvnnzfpe9x7ghf4694pgzc2fgn5hwngzq38v2nd
  - &c_cetus age1h6k2dgkjeg0c68d96r0cw4frg3eu9uyt47r7mqmv4ytm32tk04dqwp8sml
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *primary
          - *c_hercules
          - *c_cetus
