# Network subnets
[networks]
[networks.cloud]
description = "Cloud-hosted servers"
subnet = "10.77.1.0/24"
ula = "fd7d:76ee:835a:1"

[networks.homelab]
description = "Home lab servers"
subnet = "10.77.2.0/24"
ula = "fd7d:76ee:835a:2"

# Common settings
[common]
ula = "fd7d:76ee:835a"
gua = "2001:db8"

# Host definitions
[hosts.hercules]
network = "cloud"
ip_addr = "10.77.1.1"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHlRI2ynQ1ZAJWVWlk/Obhcbl+IIBDnMjvZDlWqSMvw8 rack@hercules"

[hosts.hercules.wireguard]
pubkey = "/f2YhBklUxg7Jhs8E+0ak60GNDC8mpKDNwTaNu9eaG4="
port = 51820
addrs = { v4 = "10.77.1.1", v6 = "fd7d:76ee:835a:1::1" }

[hosts.cetus]
network = "homelab"
ip_addr = "10.77.2.1"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILrsNjp641wst+zLOMlTFqQTIEUi08D5yM3AKp5+LpYL r1@cassiopeia"

[hosts.cetus.wireguard]
pubkey = "nXFAgYHgGG0Duft3WK2Aw+JhaDO76RJ4PcTg+Dy21QE="
port = 51820
addrs = { v4 = "10.77.2.1", v6 = "fd7d:76ee:835a:2::1" }

# If you want to add cassiopeia to the VPN network later:
# [hosts.cassiopeia]
# network = "homelab"
# ip_addr = "10.77.2.2"
# ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILrsNjp641wst+zLOMlTFqQTIEUi08D5yM3AKp5+LpYL r1@cassiopeia"
#
# [hosts.cassiopeia.wireguard]
# pubkey = "put_your_cassiopeia_pubkey_here="
# port = 51820
# addrs = { v4 = "10.77.2.2", v6 = "fd7d:76ee:835a:2::2" }

# You can add more hosts as needed
