name: Check flake

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.event.pull_request == null
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: airone01
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run flake check
        run: nix flake check --all-systems

